# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout currect repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install fftw
      run: |
          sudo -H apt update -y
          sudo -H apt install -y libfftw3-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install -U flake8 pytest
        pip install -U -r requirements.txt
        pip install .

    - name: Lint with flake8
      run: |
        flake8 anacal

    - name: Test with pytest
      run: |
        pytest -vv
